name: Connection Test

on:
  push:
  pull_request:
   types: [opened, synchronize]

jobs:
 send-curl:
   runs-on: ubuntu-latest

   steps:
     - name: Send curl request
       run: curl -v -X GET "https://conntest.free.beeceptor.com"