name: Connection Test

on:
  push:
  pull_request:
   types: [opened, synchronize]

jobs:
 send-curl:
   runs-on: ubuntu-latest

   steps:
     - name: Send curl request
       run: curl -u ${{ secrets.BASIC_AUTH_USERNAME }}:${{ secrets.BASIC_AUTH_PASSWORD }} -X GET "https://conntest.free.beeceptor.com"