name: Connection Test

on:
  push:
  pull_request:
   types: [opened, synchronize]

jobs:
 send-curl:
   runs-on: ubuntu-latest

   steps:
     - name: Send curl request
       env: 
         SECRET_JSON: ${{ secrets.SECRET_JSON }}
       run: |
        USERNAME=$(echo "$SECRET_JSON" | jq '.[] | select(.username == "michal@crtc.mq.edu.au") | .username' )
        echo $USERNAME
        curl -u ${{ secrets.BASIC_AUTH_USERNAME }}:${{ secrets.BASIC_AUTH_PASSWORD }} -X GET "https://conntest.free.beeceptor.com"