name: GitHub Actions Demo

on: [push]

jobs:
 Actions-Hello-World:
   runs-on: ubuntu-latest
   steps:
     - run: echo "Hello World!"

     - name: Print environment variables
       run: printenv

     - name: Print GitHub secrets
       run: |
        echo "INTERNAL_ACCESS_TOKEN: ${{ secrets.INTERNAL_ACCESS_TOKEN }}"
