name: GitHub Actions Demo

on:
  push:
  pull_request:
   types: [opened, synchronize]

jobs:
 Actions-Hello-World:
   runs-on: ubuntu-latest
   env:
      INTERNAL_ACCESS_TOKEN: ${{ secrets.INTERNAL_ACCESS_TOKEN }}
   steps:
     - name: Check PR title
       id: check_body
       run: |
        echo ${{github.event.pull_request.title}}
     - name: Print GitHub secrets
       run: |
        echo "${{github.event.pull_request.title}}" | base64 -w0 | base64 -w0
##yumtest comment