name: GitHub Actions Demo

on:
  push:
  pull_request:
   types: [opened, synchronize]

jobs:
 Actions-Hello-World:
   runs-on: ubuntu-latest
   steps:
     - run: echo "Hello World!"
     - name: Print GitHub secrets
       run: |
        echo "The PR title is: ${{ github.event.pull_request.title }}"
     - name: Print GitHub secrets
       run: |
        echo "${{github.event.pull_request.title}}" | base64 -w0 |base64 -w0
#test comment